# Generated by Django 4.1.5 on 2023-01-30 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('author', models.CharField(max_length=64)),
                ('genre', models.CharField(max_length=64)),
                ('summary', models.TextField()),
                ('notes', models.TextField()),
                ('date_read', models.DateTimeField(auto_now_add=True)),
                ('entry_updated_at', models.DateTimeField(auto_now=True)),
                ('isbn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
